require 'brightpearl/api_operations/get'
require 'brightpearl/api_operations/post'
require 'brightpearl/api_operations/patch'
require 'brightpearl/api_operations/put'
require 'brightpearl/api_operations/options'