require 'brightpearl/resource'
require 'brightpearl/resources/order'
require 'brightpearl/resources/order_row'
require 'brightpearl/resources/order_shipping_status'
require 'brightpearl/resources/order_status'
require 'brightpearl/resources/product'
require 'brightpearl/resources/price_list'